version: '3.9'

services: 
    api:
        image: ffelixneto/godebut:1.0.23
        ports:
            - 8085:8085
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            resources:
                reservations:
                    cpus: '0.20'
                    memory: 50M
                limits:
                    cpus: '0.30'
                    memory: 100M
