version: '3.9'

services:
    api:
        image: ffelixneto/godebut_dev:latest
        ports:
            - ${API_PORT}:8085
        environment:
            API_PORT : "${API_PORT}"
            DB_HOST : "${DB_HOST}"
            DB_USER : "${DB_USER}"
            DB_PASSWD : "${DB_PASSWD}"
            DB_NAME : "${DB_NAME}"
            DB_PORT : "${DB_PORT}"
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            resources:
                reservations:
                    cpus: '0.20'
                    memory: 50M
                limits:
                    cpus: '0.30'
                    memory: 100M

    db:
        image: postgres:14
        ports:
            - ${DB_PORT}:5432
        environment:
            TZ : "America/Sao_Paulo"
            POSTGRES_USER : "${DB_USER}"
            POSTGRES_PASSWORD : "${DB_PASSWD}"
            POSTGRES_DB : "${DB_NAME}"
        volumes:
            - ../pgdata:/var/lib/postgresql/data
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            resources:
                reservations:
                    cpus: '0.30'
                    memory: 100M
                limits:
                    cpus: '0.40'
                    memory: 200M
