version: '3.9'

services:
    api:
        image: ffelixneto/godebut_dev:latest
        ports:
            - 8085:8085
        environment:
            DEV_DB_HOST : "${DEV_DB_HOST}"
            DEV_DB_USER : "${DEV_DB_USER}"
            DEV_DB_PASSWD : "${DEV_DB_PASSWD}"
            DEV_DB_NAME : "${DEV_DB_NAME}"
            DEV_DB_PORT : "${DEV_DB_PORT}"
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            resources:
                reservations:
                    cpus: '0.20'
                    memory: 50M
                limits:
                    cpus: '0.30'
                    memory: 100M

    db:
        image: postgres
        ports:
            - ${DEV_DB_PORT}:5432
        environment:
            TZ : "America/Sao_Paulo"
            POSTGRES_USER : "${DEV_DB_USER}"
            POSTGRES_PASSWORD : "${DEV_DB_PASSWD}"
            POSTGRES_DB : "${DEV_DB_NAME}"
        volumes:
            - ../pgdata:/var/lib/postgresql/data
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            resources:
                reservations:
                    cpus: '0.30'
                    memory: 100M
                limits:
                    cpus: '0.40'
                    memory: 200M
